- name: create project directories
  file:
      path: "{{ project_dir }}/{{ item }}"
      state: directory
  with_items:
      - 
      - logs
      - server

- name: create virtualenv
  shell:
      cd "{{ project_dir }}";
      python3 -m venv "{{ project_dir }}/.env";
      "{{ project_dir }}/.env/bin/pip" install -U pip wheel setuptools
  args:
      executable: /bin/bash
      creates: '{{ project_dir }}/.env'

